# Generated by Django 3.2.3 on 2023-02-15 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('count', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='NativeLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_lang', models.CharField(max_length=2, unique=True)),
                ('lang', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='setting',
            field=models.CharField(choices=[('timeout_live', 'timeout_live')], max_length=20),
        ),
    ]
