# Generated by Django 3.2.3 on 2024-03-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_lang', models.CharField(max_length=2, unique=True)),
                ('lang', models.CharField(max_length=50)),
            ],
        ),
    ]
