# Generated by Django 3.2.3 on 2024-03-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_cars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='short_lang',
        ),
        migrations.AddField(
            model_name='cars',
            name='capacity',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='license',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
