# Generated by Django 3.2.3 on 2024-03-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20240314_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='capacity',
            field=models.IntegerField(blank=True, max_length=64, null=True),
        ),
    ]
