# Generated by Django 3.2.3 on 2024-03-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_carbookings_record_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbookings',
            name='record_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
