# Generated by Django 3.2.3 on 2024-04-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_carbookings_record_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=64, null=True)),
                ('detail', models.CharField(blank=True, max_length=512, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('record_timestamp', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, max_length=8, null=True)),
                ('approver', models.CharField(blank=True, max_length=64, null=True)),
                ('reason', models.CharField(blank=True, max_length=512, null=True)),
                ('update_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='carbookings',
            name='record_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carbookings',
            name='status',
            field=models.BooleanField(blank=True, max_length=8, null=True),
        ),
    ]
