# Generated by Django 3.2.3 on 2024-07-11 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20240404_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web.users'),
        ),
    ]
