# Generated by Django 3.2.3 on 2024-07-11 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_alter_leaves_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaves',
            old_name='user_id',
            new_name='user',
        ),
    ]
