# Generated by Django 3.2.3 on 2024-07-11 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_rename_user_id_leaves_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaves',
            old_name='user',
            new_name='userx',
        ),
    ]
