# Generated by Django 3.2.3 on 2024-07-15 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_rename_userx_leaves_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbookings',
            name='car_id',
        ),
        migrations.RemoveField(
            model_name='carbookings',
            name='user_id',
        ),
        migrations.AddField(
            model_name='carbookings',
            name='car',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='car_booking', to='web.cars'),
        ),
        migrations.AddField(
            model_name='carbookings',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_carbooking', to='web.users'),
        ),
    ]
